// <auto-generated />
using Checkpoint05;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Checkpoint05.Migrations
{
    [DbContext(typeof(SpaceshipContext))]
    [Migration("20180423173801_Ravioli")]
    partial class Ravioli
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Checkpoint05.Ravioli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("PackingDate");

                    b.Property<int>("SpaceshipId");

                    b.HasKey("Id");

                    b.HasIndex("SpaceshipId");

                    b.ToTable("Ravioli");
                });

            modelBuilder.Entity("Checkpoint05.Spaceship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("Checkpoint05.Ravioli", b =>
                {
                    b.HasOne("Checkpoint05.Spaceship", "Spaceship")
                        .WithMany("Ravioli")
                        .HasForeignKey("SpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
